-- Logística Flash — Supabase schema
-- Run this once in the Supabase SQL Editor (Project > SQL Editor > New query) for a fresh project.
-- Safe to re-run: every statement is idempotent (IF NOT EXISTS / OR REPLACE / DROP ... IF EXISTS).
-- This also means it doubles as a migration script — if you already ran an older
-- version of this file and later columns get added (like `messengers.origin`
-- below), just re-run the whole file again on your existing database. Nothing
-- gets dropped or overwritten; only what's missing gets added.

create extension if not exists pgcrypto;

-- ── messengers ──────────────────────────────────────────────────────────────
create table if not exists public.messengers (
  id         uuid primary key default gen_random_uuid(),
  name       text not null,
  phone      text not null,
  origin     text not null default '',
  zones      text[] not null default '{}',
  created_at timestamptz not null default now()
);
alter table public.messengers add column if not exists origin text not null default '';

-- ── clients ──────────────────────────────────────────────────────────────────
create table if not exists public.clients (
  id              uuid primary key default gen_random_uuid(),
  name            text not null,
  phone           text not null,
  address         text not null default '',
  address_details text not null default '',
  province        text not null default '',
  canton          text not null default '',
  code            text not null default '',
  created_at      timestamptz not null default now()
);
alter table public.clients add column if not exists address_details text not null default '';
alter table public.clients add column if not exists province text not null default '';
alter table public.clients add column if not exists canton text not null default '';
-- Optional second contact number (e.g. a family member's) — phone stays the
-- required primary number everything (WhatsApp, etc.) sends to by default.
alter table public.clients add column if not exists phone2 text not null default '';

-- Their own shorthand code for a client (e.g. "JG-238"), the way Nana already
-- tags people by hand today. Auto-assigned sequentially now (the app shows
-- it as "JG-01", "JG-02", ...) instead of typed by hand, so it can never
-- collide or get skipped. `generated by default as identity` (not
-- `always`) so an explicit historical number can still be inserted directly
-- later, if the real client list ever needs to be imported with the numbers
-- they already have on paper.
alter table public.clients add column if not exists code_seq integer generated by default as identity;
create unique index if not exists clients_code_seq_idx on public.clients (code_seq);

-- Replaced by code_seq above — this used to be a free-text field the admin
-- typed by hand.
drop index if exists clients_code_idx;
alter table public.clients drop column if exists code;

-- Older deployments had a single `zone` column instead of province/canton —
-- carry its value over into `province` (canton starts blank; edit each
-- client once to fill it in) rather than losing the data. Safe to run
-- whether or not `zone` still exists.
do $$
begin
  if exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'clients' and column_name = 'zone') then
    update public.clients set province = zone where (province is null or province = '') and zone is not null and zone <> '';
  end if;
end $$;

-- ── packages ─────────────────────────────────────────────────────────────────
create table if not exists public.packages (
  id            uuid primary key default gen_random_uuid(),
  tracking      text not null,
  weight        numeric(8,2),
  cost          numeric(10,2),
  client_id     uuid references public.clients(id) on delete set null,
  arrived       boolean not null default false,
  assigned_date date,
  sent          boolean not null default false,
  sent_date     date,
  created_at    timestamptz not null default now()
);
-- `sent`/`sent_date` are the terminal state: the client has paid. A package
-- only files into Historial once this is true — not the moment it's
-- delivered, since "entregado" and "cobrado" can happen on different days.
alter table public.packages add column if not exists sent boolean not null default false;
alter table public.packages add column if not exists sent_date date;
-- A tracking can be logged the moment a client forwards it, before anyone
-- knows the weight (the invoice/scale hasn't happened yet) — so both have to
-- be allowed blank until that's known.
alter table public.packages alter column weight drop not null;
alter table public.packages alter column cost drop not null;
-- Being "en bodega" with complete info no longer sends a package out by
-- itself — an admin has to explicitly assign it (`routed`) before it shows
-- up on a mensajero's route, since a ready package might still need to wait
-- (client not home that day, etc). `delivered` tracks whether the mensajero
-- actually handed it over, independent of whether it's been paid yet.
alter table public.packages add column if not exists routed boolean not null default false;
alter table public.packages add column if not exists routed_date date;
alter table public.packages add column if not exists delivered boolean not null default false;
alter table public.packages add column if not exists delivered_date date;

-- Some shipments come by boat, not plane — billed by volume (pies cúbicos),
-- not weight. shipping_type picks which of weight/cubic_feet applies;
-- validated in the app layer (always 'aereo' or 'maritimo'), not by a DB
-- constraint, matching how the rest of this schema doesn't enforce enums.
alter table public.packages add column if not exists shipping_type text not null default 'aereo';
alter table public.packages add column if not exists cubic_feet numeric(8,2);

-- A package normally goes to whichever mensajero covers the client's zone
-- (computed on the fly, not stored) — this column only exists to override
-- that for one package when there's a reason to hand it to someone else.
-- Null means "no override, use the zone's mensajero" (the default for every
-- existing row).
alter table public.packages add column if not exists messenger_id uuid references public.messengers(id) on delete set null;

-- Filled in only when a package gets matched against an uploaded factura
-- (see the invoice-review flow in js/app.js) — a manually-registered
-- package has neither until a later invoice upload matches it by tracking.
-- provider_unit_cost is what the casillero/provider charges per lb/ft³ (the
-- invoice's own "P. Unit." column); provider_line_total is that row's own
-- "TOTAL" column (unit cost × lb/ft³, as printed — not recomputed, in case
-- of rounding or extra charges the invoice applied). Both are a separate
-- thing from `cost`, which is what this app charges the client.
alter table public.packages add column if not exists invoice_number text;
alter table public.packages add column if not exists provider_unit_cost numeric(10,2);
alter table public.packages add column if not exists provider_line_total numeric(10,2);

create index if not exists packages_client_id_idx on public.packages (client_id);
create index if not exists packages_assigned_date_idx on public.packages (assigned_date);

-- Nothing used to stop the same tracking from being saved twice (double
-- submit, a race between the 2 admins, etc.) — the app's own matching logic
-- (factura, búsquedas) just takes whichever one it finds first, silently.
-- Case/whitespace-insensitive to match how the app already compares
-- trackings everywhere else (normalize() in js/app.js).
-- If this fails on first run, it means real duplicates already exist — find
-- them with:
--   select lower(trim(tracking)), array_agg(id) from public.packages
--   group by 1 having count(*) > 1;
-- and merge/delete them by hand before re-running this file.
create unique index if not exists packages_tracking_unique_idx on public.packages (lower(trim(tracking)));

-- ── app settings ─────────────────────────────────────────────────────────────
-- Single shared row (id = 1) so cost calculations (Registrar paquete, Lista
-- del día, facturas) read from one place both admins can edit, instead of a
-- hardcoded rate. Never insert or delete a second row.
create table if not exists public.app_settings (
  id          int primary key default 1,
  rate_per_lb numeric(10,2) not null default 4.25,
  crc_rate    numeric(10,2) not null default 525,
  updated_at  timestamptz not null default now(),
  constraint app_settings_singleton check (id = 1)
);
-- Defaults to 0 rather than a guessed number — there's no way to know the
-- real rate charged to clients, so the UI warns while this stays unset
-- instead of silently billing maritime packages at an invented price.
alter table public.app_settings add column if not exists price_per_cubic_ft numeric(10,2) not null default 0;
insert into public.app_settings (id) values (1) on conflict (id) do nothing;

-- When a client is deleted, its packages fall back to "sin identificar" instead
-- of silently keeping a stale "assigned today" date with no client attached.
create or replace function public.clear_assigned_date_on_client_delete()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.packages set assigned_date = null where client_id = old.id;
  return old;
end;
$$;

drop trigger if exists trg_clear_assigned_date_on_client_delete on public.clients;
create trigger trg_clear_assigned_date_on_client_delete
before delete on public.clients
for each row execute function public.clear_assigned_date_on_client_delete();

-- ── Row Level Security ───────────────────────────────────────────────────────
-- Only the 2 admins (created as Supabase Auth users) sign in, and every signed-in
-- user shares the exact same data — there's no per-row ownership in this app, so
-- policies simply require "you are logged in" for every operation.

alter table public.messengers   enable row level security;
alter table public.clients      enable row level security;
alter table public.packages     enable row level security;
alter table public.app_settings enable row level security;

drop policy if exists "authenticated read messengers"   on public.messengers;
drop policy if exists "authenticated write messengers"  on public.messengers;
drop policy if exists "authenticated update messengers" on public.messengers;
drop policy if exists "authenticated delete messengers" on public.messengers;
create policy "authenticated read messengers"   on public.messengers for select to authenticated using (true);
create policy "authenticated write messengers"  on public.messengers for insert to authenticated with check (true);
create policy "authenticated update messengers" on public.messengers for update to authenticated using (true) with check (true);
create policy "authenticated delete messengers" on public.messengers for delete to authenticated using (true);

drop policy if exists "authenticated read clients"   on public.clients;
drop policy if exists "authenticated write clients"  on public.clients;
drop policy if exists "authenticated update clients" on public.clients;
drop policy if exists "authenticated delete clients" on public.clients;
create policy "authenticated read clients"   on public.clients for select to authenticated using (true);
create policy "authenticated write clients"  on public.clients for insert to authenticated with check (true);
create policy "authenticated update clients" on public.clients for update to authenticated using (true) with check (true);
create policy "authenticated delete clients" on public.clients for delete to authenticated using (true);

drop policy if exists "authenticated read packages"   on public.packages;
drop policy if exists "authenticated write packages"  on public.packages;
drop policy if exists "authenticated update packages" on public.packages;
drop policy if exists "authenticated delete packages" on public.packages;
create policy "authenticated read packages"   on public.packages for select to authenticated using (true);
create policy "authenticated write packages"  on public.packages for insert to authenticated with check (true);
create policy "authenticated update packages" on public.packages for update to authenticated using (true) with check (true);
create policy "authenticated delete packages" on public.packages for delete to authenticated using (true);

drop policy if exists "authenticated read settings"   on public.app_settings;
drop policy if exists "authenticated update settings" on public.app_settings;
create policy "authenticated read settings"   on public.app_settings for select to authenticated using (true);
create policy "authenticated update settings" on public.app_settings for update to authenticated using (true) with check (true);

-- ── Optional: sample data ────────────────────────────────────────────────────
-- Uncomment to preload the same example data the design prototype shipped with.
-- Safe to run once on an empty database only (it doesn't check for existing rows).
--
-- insert into public.messengers (name, phone, origin, zones) values
--   ('Mensajero 1', '8880-1111', 'https://waze.com/ul/hd6', array['Heredia','Alajuela']),
--   ('Mensajero 2', '8880-2222', 'https://maps.app.goo.gl/exampleSJ', array['San José']),
--   ('Mensajero 3', '8880-3333', 'https://maps.app.goo.gl/exampleCartago', array['Cartago']);
--
-- insert into public.clients (name, phone, address, province, canton) values
--   ('María Fernández Solís', '8888-1234', 'https://waze.com/ul/hd12345', 'Heredia', 'Heredia'),
--   ('Carlos Ramírez Vargas', '8712-4455', 'https://waze.com/ul/al56789', 'Alajuela', 'Alajuela'),
--   ('Ana Sofía Chaves',      '8399-2210', 'https://maps.app.goo.gl/sanjose01', 'San José', 'Curridabat');
